---
title: "Genotype by Environment analysis using RAP"
author: "Bart-Jan van Rossum"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: false
    number_sections: true
bibliography: bibliography.bib
vignette: >
  %\VignetteIndexEntry{Genotype by Environment analysis using RAP}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>",
fig.dim = c(7, 5)
)
library(RAP)
```

# Genotype by Environment Analysis using the RAP package

The RAP package is developed as an easy to use package for analysing data of 
plant breeding experiments with plenty of options for plotting and reporting 
the results of the analyses.  

The package has 3 main components:

* Modeling trial data for single trials and extracting results
* Genotype by Environment (GxE) analysis
* QTL analysis

This vignette deals with the GxE part of the package and describes in 
detail how to perform the different types of analysis that are available in the package.

The following types of analysis can be done using RAP:

* [Best variance-covariance model](#vc)
* [AMMI Analysis](#am)
* [Finlay-Wilkinson Analysis](#fw)
* [Computation of mega-environments](#me)
* [Computation of stability measures](#st)

---

# Data preparation

Just as for the analysis of single field trials the input for GxE analysis in the RAP package is an object of class TD. For a detailed description on how to construct such an object see [Modeling field trials using RAP](RAP.html). For this vignette the TD object created in the final step of [Modeling field trials using RAP](RAP.html) will be used as analysis object.

# Best variance-covariance model {#vc}

# AMMI Analysis {#am}

# Finlay-Wilkinson Analysis {#fw}

# Computation of mega-environments {#me}

# Computation of stability measures {#st}

----

# References
