%-------------------------------------------------------------------------------
%	Packages and other Document configurations
%-------------------------------------------------------------------------------
\documentclass[a4paper,11pt]{article}
% Package declaration
%-------------------------------------------------------------------------------
% Specify input encoding
\usepackage[utf8]{inputenc}
% For A4 paper set all margins to 3cm
\usepackage[paper=a4paper,left=1.5cm,top=2cm,right=1.5cm,bottom=2cm]{geometry}%
% Set linespace, usage \doublespacing \singlespacing \onehalfspacing
\usepackage{setspace}%
% Set palatino font with small caps as default
\usepackage[sc]{mathpazo}%
% Rotation tools, including rotated full-page floats.
\usepackage{rotating}%
% Create subfigures
\usepackage{subfigure}%
% Extensive support for hypertext in LaTeX
\usepackage{hyperref}%
% For adding bookmarks to the document
\usepackage{bookmark}%
% For adding time to the document
\usepackage{datetime}
% For alignment of captions
\usepackage{caption}
% For multiple columns.
\usepackage{multicol}

% Start Article header
%-------------------------------------------------------------------------------
% Title
\title{AMMI report for \Sexpr{x$trait}}%
% Authors
\author{\vspace{-5ex}}
%-------------------------------------------------------------------------------
% Dates
\date{\vspace{-5ex}}
%-------------------------------------------------------------------------------
% End article header

% For left aligning captions
\captionsetup{justification=raggedright,singlelinecheck=false}

% Start Document
%-------------------------------------------------------------------------------
\begin{document}

% Article title and date.
\maketitle
% Start single line spacing
\singlespacing

%-------------------------------------------------------------------------------
\section{General information}
%-------------------------------------------------------------------------------
<<label=general, echo=FALSE, results="asis">>=
bgItems <- c(format(attr(x, "timestamp"), "%y-%m-%d %H:%M:%S"),
             as.character(packageVersion("RAP")))
names(bgItems) <- c("Analysis done on",
                    "Pipeline version")
print(xtable::xtable(x = data.frame(bgItems), label = "general",
                     align = c("l", "l")),
      latex.environments = "flushleft", hline.after = NULL,
      include.rownames = TRUE, include.colnames = FALSE)
@

%-------------------------------------------------------------------------------
\section{Anova table}
%-------------------------------------------------------------------------------

<<label=anova, echo=FALSE, results="asis">>=
anovaTab <- x$anova
## Add significance stars
anovaTab[, ncol(anovaTab) + 1] <- symnum(x = anovaTab[, ncol(anovaTab)],
                                         corr = FALSE, na = FALSE,
                                         cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1),
                                         symbols = c("***", "**", "*", ".", " "))
colnames(anovaTab)[ncol(anovaTab)] <- ""
rownames(anovaTab)[which(rownames(anovaTab) %in% c("genotype", "trial"))] <-
  c("Genotype", "Environment")
legendText <- "Significance codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1} \\\\"
print(xtable::xtable(x = anovaTab, label = "anova",
                     align = c("l", "r", "r", "r", "r", "r", "l"),
                     digits = c(0, 0, 0, 0, 2, -2, 0),
                     display = c("s", "f", "f", "f", "f", "e", "s")),
      latex.environments = "flushleft",
      include.rownames = TRUE, include.colnames = TRUE,
      add.to.row = list(pos = list(nrow(anovaTab)),
                        command = paste0("\\hline  \\multicolumn{",
                                         ncol(anovaTab), "}{c}{",
                                         legendText)))
@
\clearpage
%-------------------------------------------------------------------------------
\section{PCA Summaries}
%-------------------------------------------------------------------------------

<<label=importance, echo=FALSE, results="asis">>=
importance <- x$importance[, 1:ncol(x$envScores)]
print(xtable::xtable(x = importance, label = "importance",
                     align = c("l", rep("c", ncol(importance)))),
      latex.environments = "flushleft",
      include.rownames = TRUE, include.colnames = TRUE)
@

<<label=impPlot, echo=FALSE, fig.height=4, fig.width=5, fig.align="left">>=
plot(x = 1:ncol(x$importance), y = x$importance[2, ], type = "b",
     xaxt = "n", xlab = "", ylab = "")
axis(side = 1, at = 1:ncol(x$importance), labels = colnames(x$importance))
@
\newpage

%-------------------------------------------------------------------------------
\section{Biplot}
%-------------------------------------------------------------------------------
<<label=biplot, echo=FALSE>>=
plot(x, plotType = "AMMI2")
@

%-------------------------------------------------------------------------------
% End Document
\end{document}
