%-------------------------------------------------------------------------------
%	Packages and other Document configurations
%-------------------------------------------------------------------------------
\documentclass[a4paper,11pt]{article}
% Package declaration
%-------------------------------------------------------------------------------
% Needed for draftwatermark
%\usepackage{xcolor}
% For adding a watermark
%\usepackage[printwatermark]{xwatermark}
% Specify input encoding
\usepackage[utf8]{inputenc}
% For A4 paper set all margins to 3cm
\usepackage[paper=a4paper,left=1.5cm,top=2cm,right=1.5cm,bottom=2cm]{geometry}%
% Set linespace, usage \doublespacing \singlespacing \onehalfspacing
\usepackage{setspace}%
% Set palatino font with small caps as default
\usepackage[sc]{mathpazo}%
% Create author affiliation
\usepackage[noblocks]{authblk}%
% Make references as [1-4], not [1,2,3,4]
\usepackage{cite}%
% Rotation tools, including rotated full-page floats.
\usepackage{rotating}%
% Create subfigures
\usepackage{subfigure}%
% Publication quality tables in LaTeX
\usepackage{booktabs}%
% Required to insert dummy text (Lorem Ipsum)
\usepackage{lipsum}%
% Extensive support for hypertext in LaTeX
\usepackage{hyperref}%

% For adding bookmarks to the document
\usepackage{bookmark}%
% For adding time to the document
\usepackage{datetime}
% For alignment of captions
\usepackage{caption}

% Graphics Path definition
%-------------------------------------------------------------------------------
\graphicspath{{figures/}}

% newcommand
%-------------------------------------------------------------------------------
%\newcommand{\scscst}{\scriptscriptstyle}
%\newcommand{\scst}{\scriptstyle}
%\newcommand{\Robject}[1]{{\texttt{#1}}}
%\newcommand{\Rfunction}[1]{{\texttt{#1}}}
%\newcommand{\Rclass}[1]{\textit{#1}}
%\newcommand{\Rpackage}[1]{\textit{#1}}
%\newcommand{\Rexpression}[1]{\texttt{#1}}
%\newcommand{\Rmethod}[1]{{\texttt{#1}}}
%\newcommand{\Rfunarg}[1]{{\texttt{#1}}}

% Redefine commands
%-------------------------------------------------------------------------------
% Set affiliation font to small font size
\renewcommand{\Affilfont}{\normalfont\small}%
% Set table numbering to Roman, i.e. I,II etc. instead of default arabic 1,2 etc.
\renewcommand{\thetable}{\arabic{table}}%\Roman{table}

% Redefine abstract environment
%-------------------------------------------------------------------------------
\def\@abstractline{\textwidth}
\renewenvironment{abstract}
{
\ifhmode\begingroup\parskip0pt\par\noindent\endgroup\fi%
\begin{rmfamily}
%\vspace{1cm} % use \topsep in list
{\noindent\bfseries\large\abstractname\vspace{-0.5em}}
{\par\vbox{\hrule width \@abstractline}}
}{
\ifhmode\begingroup\parskip0pt\par\noindent\endgroup\fi %
\par\vbox{\hrule width \@abstractline}% \vspace{1cm} %
\end{rmfamily}
}

%-------------------------------------------------------------------------------
%	Article Information
%-------------------------------------------------------------------------------
% Setting PDF properties in the final PDF
% !! Works only with PDFLaTeX and LaTeX->DVI->PS->PDF
\hypersetup
{
pdfsubject={Model report},
pdftitle={Model report}
}
% % !! Works with LaTeX->DVI->PDF
% \special{pdf: docinfo <<
% /Author (Maikel Verouden)
% /Subject (Field Layout 2016 SESVanderHave : Exploratory Analysis)
% /Title (Field Layout 2016 SESVanderHave : Exploratory Analysis.)
% /Keywords (SESVanderHave, Sugar beet, Field trials, Clean Data, Exploratory Analysis)
% >>}

% Start Article header
%-------------------------------------------------------------------------------
% Title
\title{Model report}%
% Authors
\author{\vspace{-5ex}}
%-------------------------------------------------------------------------------
% Affiliations
% When an affiliation becomes too large to fit the page, continue using the command \newline e.g.
% \affil[a]{Place Groupname, Name of the Research Institute, Name of the University,\newline P.O. Box 90210, ZIPCODE City Name, Country Name}%
%\affil[a]{Wageningen University \& Research, Biometris, P.O. Box 16,\newline 6700 AA Wageningen, The Netherlands}%
%\affil[b]{Former Affiliation, P.O. Box 3, zipcode Somecity, Country}%

% Dates
\date{\today\ \currenttime} % when you are in the process of writing
%\date{Submitted: Month Day, Year}  % when the article has been submitted for review
%\date{Received: Month Day, Year; Revised: Month Day, Year; Accepted: Month Day, Year;} % when accepted
%-------------------------------------------------------------------------------
% End article header

% Hyphenation \hyphenation{words} words separated by spaces
% hypenated words can break at the hyphen non hyphenated words are not allowed to be hyphenated
% e.g. \hyphenation{FORTRAN Hy-phen-a-tion} will hyphenate:
% hyphenation as well as Hyphenation, but not
% fortran or FORTRAN
\hyphenation{Rep-li-cates}

% For left aligning captions
\captionsetup{justification=raggedright,singlelinecheck=false}

% Start Document
%-------------------------------------------------------------------------------
\begin{document}

% Set knitr options
<<label=setup, include=FALSE, cache=FALSE>>=
## load required packages
lapply(list("SpATS", "xtable"), library, character.only = TRUE)
## Set global chunk options
knitr::opts_chunk$set(dev = c("pdf"),
                      fig.path = "figures/fig-",
                      fig.align = "center",
                      fig.show = "hold",
                      tidy = TRUE)
@
<<label=extractInfo, echo=FALSE, include=FALSE>>=
## Extract basic modelling information
engine <- x$engine
if (is.null(x$mFix)) {
  model <- x$mRand[[1]]
  modelType <- "random"
} else {
  model <- x$mFix[[1]]
  modelType <- "fixed"
}
@

% Article title, Authors and Affiliations
\maketitle
%\newpage

% Start double line spacing
\singlespacing
%\doublespacing

% % Abstract
% \begin{abstract}
% \noindent \lipsum[1]
% \end{abstract}
% % Keywords
% \noindent\textbf{KEYWORDS:~}SESVanderHave, Sugar beet, Field trials, Clean Data, Exploratory Analysis%
% \newpage

% Table of Contents
%\tableofcontents
%\newpage

%-------------------------------------------------------------------------------
\section{Description of the fitted model}
%-------------------------------------------------------------------------------

<<label=modelDescription, echo=FALSE, results="asis">>=
#model <- if (is.null(x$mFix)) x$mRand[[1]] else x$mFix[[1]]
modelDesigns <- c("block (R)",
                  "replicate (F) + block(replicate) (R)",
                  "replicate (F)",
                  "row (R) + col (R)",
                  "replicate (F) + row(replicate) (R) + col(replicate) (R)")
names(modelDesigns) <- c("ibd", "res.ibd", "rcbd", "rowcol", "res.rowcol")
if (length(grep(pattern = "checkId",
                x = deparse(model$model$fixed))) > 0) {
  modelDesigns <- paste("checkId (F) +", modelDesigns)
}
descrItems <- c(x$traits, modelDesigns[x$design],
                if (engine == "SpATS") "2 dimensional P-splines" else "no",
                modelType)
names(descrItems) <- c("Trait",
                       "Experimental design features",
                       "Spatial model",
                       "Genotype")
print(xtable::xtable(x = data.frame(descrItems), label = "modelDescription",
                     align = c("l", "l")),
      latex.environments = "flushleft", hline.after = NULL,
      include.rownames = TRUE, include.colnames = FALSE)
@

%-------------------------------------------------------------------------------
\section{Summary of the results}
%-------------------------------------------------------------------------------
<<label=extrSummary, echo=FALSE, results="hide">>=
## Create summary SpATS in seperate chunck to suppress output.
if (engine == "SpATS") {
  SpATSSum <- summary(model)
}
@
<<label=summary, echo=FALSE, results="asis">>=
modSum <- as.data.frame(summary(x$data, traits = x$traits))
modSum <- modSum[!is.na(modSum$Freq), ]
print(xtable::xtable(x = modSum[, c(1, 3)],
                     caption = "Size of the data set and eight number descriptives",
                     label = "modelSummary",
                     align = c("l", "l", "r")),
      latex.environments = "flushleft", caption.placement = "top",
      include.rownames = FALSE, include.colnames = FALSE)
@
<<label=condNewpage, echo=FALSE, results="hide">>=
if (engine == "SpATS") {
  "\newpage"
}
@
<<label=SpATSsummary, echo=FALSE, results="asis">>=
if (engine == "SpATS") {
  "\newpage"
  ## Print table of effective dimensions
  effDims <- SpATSSum$p.table.dim
  rownames(effDims)[is.na(rownames(effDims))] <- ""
  renameFrom <- c("genotype", "repId", "repId:rowId", "repId:colId",
                  "colCoordinates", "rowCoordinates", "rowCoordinatescolCoordinates",
                  "f(colCoordinates)", "f(rowCoordinates)",
                  "f(colCoordinates):rowCoordinates",
                  "colCoordinates:f(rowCoordinates)",
                  "f(colCoordinates):f(rowCoordinates)")
  renameTo <- c("Genotype", "Replicate", "Row(replicate)", "Col(replicate)",
                "Lineair trend along cols", "Lineair trend along rows",
                "Lineair trend along rows and cols",
                "Smooth trend along cols", "Smooth trend along rows",
                "Lineair trend in rows changing smoothly along cols",
                "Lineair trend in cols changing smoothly along rows",
                "Smooth-by-smooth interaction trend over rows and cols")
  for (i in 1:length(renameFrom)) {
    rownames(effDims)[which(rownames(effDims) == renameFrom[i])] <- renameTo[i]
  }
  print(xtable::xtable(x = effDims, caption = "Effective dimensions",
                       label = "effDims",
                       align = c("l", "c", "c", "c", "c", "c")),
        latex.environments = "flushleft", caption.placement = "top",
        include.rownames = TRUE)
  ## Print generalized heritability
  if (modelType == "random") {
    cat(paste("The generalized heritability is",
              round(STExtract(x, what = "heritability"), 2)))
  }
  ## Print table of variance components.
  varComp <- SpATSSum$p.table.vc
  rownames(varComp)[is.na(rownames(varComp))] <- ""
  for (i in 1:length(renameFrom)) {
    rownames(varComp)[which(rownames(varComp) == renameFrom[i])] <- renameTo[i]
  }
  print(xtable::xtable(x = varComp[, 1, drop = FALSE], label = "varComps",
                       caption =  "Variance components",
                       align = c("l", "c")),
        latex.environments = "flushleft", caption.placement = "top",
        include.rownames = TRUE)
}
@
\clearpage

%-------------------------------------------------------------------------------
\section{Diagnostic plots}
%-------------------------------------------------------------------------------
<<label=SpATSPlots, echo=FALSE>>=
## SpATS specific plots
if (engine == "SpATS") {
  plot(model)
}
@
<<condNewpage>>=
@
<<label=basePlots, echo=FALSE>>=
## Base diagnostic plots, identical for all models
plot(x, what = modelType, plotType = "base")
@
\newpage
<<label=best20, echo=FALSE, results="hide">>=
best <- summary(x)
@
%-------------------------------------------------------------------------------
\section{List of best \Sexpr{nrow(best)} genotypes}
%-------------------------------------------------------------------------------
<<label=printBest20, echo=FALSE, results="asis">>=
print(xtable::xtable(x = best[-1], label = "bestTab",
                     align = c("l", "c", "c"), digits = c(0, 2, 2)),
      latex.environments = "flushleft",
      include.rownames = TRUE)

@

%\newpage

% References
%-------------------------------------------------------------------------------
% This article template provides 2 bibliography styles:
% jchemometr.bst, which follows the bibliography style of the Journal of Chemometrics (Wiley)
% chemolab.bst  , which follows the bibliography style of Chemometrics and Intelligent Laboratory Systems (Elsevier)
% It also includes:
% abbrev.bib    , which contains codes for journal names and will print the journal name abbreviation
% jnames.bib    , which contains codes for journal names and will print the full journal name
% The article bibliography allows for definition of additional journal codes
%
% When you need a specific bibliography style for a journal, which does not have its style available on the internet,
% you can create it yourself using the custom-bib package for LaTeX (check CTAN).
%------------------------------------------------------------------------------
%\bibliographystyle{style/jchemometr.bst}% \bibliographystyle{style/chemolab.bst}
%\bibliography{bibliography/abbrev.bib,% \bibliography{bibliography/jnames.bib,
%bibliography/bibliography.bib}% Bibliography file for the article (usually '*.bib')
%-------------------------------------------------------------------------------

%-------------------------------------------------------------------------------
% Handy to include this at the end
%-------------------------------------------------------------------------------
%\section*{SessionInfo}
%-------------------------------------------------------------------------------
<<sessionInfo, echo=FALSE>>=
#sessionInfo()
@
%-------------------------------------------------------------------------------

%' % Detach packages loaded in this article
%' %-------------------------------------------------------------------------------
%' <<UnloadPackages, echo=FALSE, include=FALSE>>=
%' detach("package:fields", unload=TRUE)
%' detach("package:spam", unload=TRUE)
%' detach("package:grid", unload=TRUE)
%' detach("package:maps", unload=TRUE)
%' detach("package:reshape2", unload = TRUE)
%' detach("package:xtable", unload = TRUE)
%' @
%-------------------------------------------------------------------------------
% End Document
\end{document}
