%-------------------------------------------------------------------------------
%	Packages and other Document configurations
%-------------------------------------------------------------------------------
\documentclass[a4paper,11pt]{article}
% Package declaration
%-------------------------------------------------------------------------------
% Specify input encoding
\usepackage[utf8]{inputenc}
% For A4 paper set all margins to 3cm
\usepackage[paper=a4paper,left=1.5cm,top=2cm,right=1.5cm,bottom=2cm]{geometry}%
% Set linespace, usage \doublespacing \singlespacing \onehalfspacing
\usepackage{setspace}%
% Set palatino font with small caps as default
\usepackage[sc]{mathpazo}%
% Rotation tools, including rotated full-page floats.
\usepackage{rotating}%
% Create subfigures
\usepackage{subfigure}%
% Extensive support for hypertext in LaTeX
\usepackage{hyperref}%
% For adding bookmarks to the document
\usepackage{bookmark}%
% For adding time to the document
\usepackage{datetime}
% For alignment of captions
\usepackage{caption}
% For multiple columns.
\usepackage{multicol}
% For properly printing a ~
\usepackage{textcomp}

% Start Article header
%-------------------------------------------------------------------------------
% Title
\title{Multi QTL model fit report}%
% Authors
\author{\vspace{-5ex}}
%-------------------------------------------------------------------------------
% Dates
\date{\vspace{-5ex}}
%-------------------------------------------------------------------------------
% End article header

% For left aligning captions
\captionsetup{justification=raggedright,singlelinecheck=false}

% Start Document
%-------------------------------------------------------------------------------
\begin{document}

% Load required packages
<<label=setup, include=FALSE, cache=FALSE>>=
## load required packages
lapply(list("qtl"), library, character.only = TRUE)
summ <- summary(x$qtl)
@

% Article title and date.
\maketitle
% Start single line spacing
\singlespacing

%-------------------------------------------------------------------------------
\section{General information}
%-------------------------------------------------------------------------------
<<label=general, echo=FALSE, results="asis">>=
bgItems <- c(format(attr(x, "timestamp"), "%y-%m-%d %H:%M:%S"),
             as.character(packageVersion("RAP")))
names(bgItems) <- c("Analysis done on",
                    "Pipeline version")
print(xtable::xtable(x = data.frame(bgItems), label = "general",
                     align = c("l", "l")),
      latex.environments = "flushleft", hline.after = NULL,
      include.rownames = TRUE, include.colnames = FALSE)
@

%-------------------------------------------------------------------------------
\section{Model}
%-------------------------------------------------------------------------------
<<label=model, echo=FALSE, results="asis">>=
fitted <- x$QTLDet$peaks[-3]
print(xtable::xtable(x = fitted, caption = "List of fitted candidate QTLs",
                     label = "fitted",
                     align = c("l", "r", "r", "r")),
      latex.environments = "flushleft",
      include.rownames = TRUE, include.colnames = TRUE,
      caption.placement = "top")

if (!is.null(x$qtl$result.drop)) {
  modNames <- x$QTLDet$peaks[rownames(x$qtl$result.drop), "altName"]
} else {
  modNames <- x$QTLDet$peaks$altName
}
## Because of the ~ in the formula no sanitize has to be applied on the
## separate parts of the formula and the sanitize function for the whole
## object has to be set to identity.
modSum <- data.frame(c("Selection", "Threshold", "Window", "Final model"),
                     c(x$selection, x$thr, x$QTLDet$info$window,
                     paste(xtable::sanitize(x$QTLDet$trait), "\\texttildelow\\",
                       xtable::sanitize(paste(modNames, collapse = " + ")))))
## When no selection was done remove threshold and window from model summary.
if (x$selection == "none") {
  modSum <- modSum[c(1, 4), ]
}
print(xtable::xtable(x = modSum, caption = "Model",
                     label = "model",
                     align = c("l", "l", "l")),
      latex.environments = "flushleft", hline.after = NULL,
      include.rownames = FALSE, include.colnames = FALSE,
      caption.placement = "top", sanitize.text.function = identity)
@
\clearpage
%-------------------------------------------------------------------------------
\section{Summary}
%-------------------------------------------------------------------------------
<<label=summary, echo=FALSE, results="asis">>=
print(xtable::xtable(x = summ$result.full, caption = "Full model result",
                     label = "modRes",
                     align = c("l", "r", "r", "r", "r", "r", "r", "r"),
                     digits = c(0, 0, 0, 0, 2, 2, 2, 2),
                     display = c("s", "f", "f", "f", "f", "f", "e", "e")),
      latex.environments = "flushleft", include.rownames = TRUE,
      include.colnames = TRUE, caption.placement = "top")
@
%-------------------------------------------------------------------------------
<<label=anova, echo=FALSE, results="asis", eval=!is.null(summ$result.drop)>>=
cat("\\section{Anova}")
anovaTab <- data.frame(summ$result.drop, check.names = FALSE)
## Add significance stars.
anovaTab[, ncol(anovaTab) + 1] <- symnum(x = anovaTab[, ncol(anovaTab)],
                                         corr = FALSE, na = FALSE,
                                         cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1),
                                         symbols = c("***", "**", "*", ".", " "))
colnames(anovaTab)[ncol(anovaTab)] <- ""
legendText <- "Significance codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1} \\\\"
print(xtable::xtable(x = anovaTab, label = "anova",
                     align = c("l", "r", "r", "r", "r", "r", "r", "r", "l"),
                     digits = c(0, 0, 0, 2, 2, 2, 2, 2, 0),
                     display = c("s", "f", "f", "f", "f", "f", "e", "e", "s")),
      latex.environments = "flushleft", include.rownames = TRUE,
      include.colnames = TRUE,
      add.to.row = list(pos = list(nrow(anovaTab)),
                        command = paste0("\\hline  \\multicolumn{",
                                         ncol(anovaTab), "}{c}{",
                                         legendText)))
cat("\\clearpage")
@
%-------------------------------------------------------------------------------
\section{Effects}
%-------------------------------------------------------------------------------
<<label=effects, echo=FALSE, results="asis">>=
effectTab <- data.frame(estimate = x$qtl$ests$ests,
                        SE = sqrt(diag(x$qtl$ests$covar)))
## Add significance stars.
print(xtable::xtable(x = effectTab, label = "effects",
                     align = c("l", "r", "r"),
                     digits = c(0, 2, 2)),
      latex.environments = "flushleft",
      include.rownames = TRUE, include.colnames = TRUE)
@
%-------------------------------------------------------------------------------
% End Document
\end{document}
