%-------------------------------------------------------------------------------
%	Packages and other Document configurations
%-------------------------------------------------------------------------------
\documentclass[a4paper,11pt]{article}
% Package declaration
%-------------------------------------------------------------------------------
% Specify input encoding
\usepackage[utf8]{inputenc}
% For A4 paper set all margins to 3cm
\usepackage[paper=a4paper,left=1.5cm,top=2cm,right=1.5cm,bottom=2cm]{geometry}%
% Set linespace, usage \doublespacing \singlespacing \onehalfspacing
\usepackage{setspace}%
% Set palatino font with small caps as default
\usepackage[sc]{mathpazo}%
% Rotation tools, including rotated full-page floats.
\usepackage{rotating}%
% Create subfigures
\usepackage{subfigure}%
% Extensive support for hypertext in LaTeX
\usepackage{hyperref}%
% For adding bookmarks to the document
\usepackage{bookmark}%
% For adding time to the document
\usepackage{datetime}
% For alignment of captions
\usepackage{caption}
% For multiple columns.
\usepackage{multicol}

% Start Article header
%-------------------------------------------------------------------------------
% Title
\title{QTL Detection report}%
% Authors
\author{\vspace{-5ex}}
%-------------------------------------------------------------------------------
% Dates
\date{\vspace{-5ex}}
%-------------------------------------------------------------------------------
% End article header

% For left aligning captions
\captionsetup{justification=raggedright,singlelinecheck=false}

% Start Document
%-------------------------------------------------------------------------------
\begin{document}

% Load required packages
<<label=setup, include=FALSE, cache=FALSE>>=
## load required packages
lapply(list("qtl"), library, character.only = TRUE)
@

% Article title and date.
\maketitle
% Start single line spacing
\singlespacing

%-------------------------------------------------------------------------------
\section{General information}
%-------------------------------------------------------------------------------
<<label=general, echo=FALSE, results="asis">>=
bgItems <- c(format(attr(x, "timestamp"), "%y-%m-%d %H:%M:%S"),
             as.character(packageVersion("RAP")))
names(bgItems) <- c("Analysis done on",
                    "Pipeline version")
print(xtable::xtable(x = data.frame(bgItems), label = "general",
                     align = c("l", "l")),
      latex.environments = "flushleft", hline.after = NULL,
      include.rownames = TRUE, include.colnames = FALSE)
@
%-------------------------------------------------------------------------------
\section{Model}
%-------------------------------------------------------------------------------
<<label=model, echo=FALSE, results="asis">>=
modSum <- data.frame(c("QTL Detection model", "Method", "Step size",
                       "Window"),
                     c(switch(x$type, "MR" = "Marker response",
                               "SIM" = "Simple interval mapping",
                               "CIM" = "Composite interval mapping"),
                       "Haley Knot", x$info$step, x$info$window))
print(xtable::xtable(x = modSum, label = "model",
                     align = c("l", "l", "l")),
      latex.environments = "flushleft", hline.after = NULL,
      include.rownames = FALSE, include.colnames = FALSE)
@
%-------------------------------------------------------------------------------
\section{Summary}
%-------------------------------------------------------------------------------
<<label=summary, echo=FALSE, results="asis">>=
summaryTab <- x$peaks
if (nrow(summaryTab) > 0) {
  print(xtable::xtable(x = summaryTab,
                       caption = "List of candidate QTLs (peaks)",
                       label = "summary",
                       align = c("l", "r", "r", "r", "r"),
                       digits = c(0, 0, 0, 0, 2)),
        latex.environments = "flushleft",
        include.rownames = TRUE, include.colnames = TRUE,
        caption.placement = "top")
} else {
  cat("No peaks detected")
}
@
\newpage
%-------------------------------------------------------------------------------
\section{Profile plot}
%-------------------------------------------------------------------------------
<<label=profile, echo=FALSE, fig.align="left">>=
plot(x)
@
%-------------------------------------------------------------------------------
% End Document
\end{document}
