---
title: "Use of RAP package"
author: "Bart-Jan van Rossum"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: bibliography.bib
vignette: >
  %\VignetteIndexEntry{Use of RAP package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

General introduction about package

## Create TD object

The first step when modeling a field trial or performing a GxE analysis using 
the RAP package will always be creating an object of class TD. Such an object
is used internally by the package for performing all types of analysis.  
A TD object can be easily created from a data.frame by calling the function
*createTD*. This function will do a couple of things:  
* Rename columns to default column names used by the RAP package. For example, 
the column in the data containing variety/accession/genotype will allways be 
renamed to genotype. Original column names will be stored as an attribute to 
the final object of class TD.
* Convert column type to the default column types. For example the column 
genotype will always be converted to a factor and rowCoord will always be 
converted to a numeric column.
* Split the data by trial. The output TD object will be a list of data.frames
where each data.frame contains the data for a single trial. If there is only 
one trial or no column trial is defined the output will be a list with one
item only.
* Add meta data to the seperate data.frames in 



## Modeling

Explanation on how to do basic modeling using a TD object  
$Y = X\beta + \epsilon$  
test[see @Rodrguezlvarez2017]

## Extract 

Explanation on what can be extracted from a model and how

## References


